// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKy2a2tCCAcY6sTKW5yxeGIuilrFDZksw',
    appId: '1:454553956094:web:6e1c4c1c0c6b697f8e3faf',
    messagingSenderId: '454553956094',
    projectId: 'union-shop-190ff',
    authDomain: 'union-shop-190ff.firebaseapp.com',
    storageBucket: 'union-shop-190ff.firebasestorage.app',
    measurementId: 'G-0FECEYM1KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9lGVVctCmcQU1bFQxgN0C6c6j4zKVsFI',
    appId: '1:454553956094:android:81c10ae08b1970998e3faf',
    messagingSenderId: '454553956094',
    projectId: 'union-shop-190ff',
    storageBucket: 'union-shop-190ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY2-EnDT4dbzOY8BG_KYakEvLWZPaQ7Uk',
    appId: '1:454553956094:ios:8f545aa17e6088ac8e3faf',
    messagingSenderId: '454553956094',
    projectId: 'union-shop-190ff',
    storageBucket: 'union-shop-190ff.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY2-EnDT4dbzOY8BG_KYakEvLWZPaQ7Uk',
    appId: '1:454553956094:ios:8f545aa17e6088ac8e3faf',
    messagingSenderId: '454553956094',
    projectId: 'union-shop-190ff',
    storageBucket: 'union-shop-190ff.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKy2a2tCCAcY6sTKW5yxeGIuilrFDZksw',
    appId: '1:454553956094:web:82ab22e81a7e1b1e8e3faf',
    messagingSenderId: '454553956094',
    projectId: 'union-shop-190ff',
    authDomain: 'union-shop-190ff.firebaseapp.com',
    storageBucket: 'union-shop-190ff.firebasestorage.app',
    measurementId: 'G-ZVKPEKR137',
  );
}
