import 'package:json_annotation/json_annotation.dart';

// This file will be generated by the build_runner.
// It connects this file to the generated code.
part 'product.g.dart';

// This annotation tells the generator to create serialization logic for this class.
@JsonSerializable()
class Product {
  final String id; // Unique identifier from Firebase
  final String title; // "Classic Hoodie - Purple"
  final String price; // "£25.00"
  final double priceValue; // 25.00 (for sorting)
  final String category; // "Clothing"
  final int popularity; // 95 (0-100 scale)
  final bool featured; // true/false
  final String imageUrl; // URL to product image

  Product({
    required this.id,
    required this.title,
    required this.price,
    required this.priceValue,
    required this.category,
    required this.popularity,
    required this.featured,
    required this.imageUrl,
  });

  // Connects to the generated code for deserialization.
  factory Product.fromJson(Map<String, dynamic> json) => _$ProductFromJson(json);

  // Connects to the generated code for serialization.
  Map<String, dynamic> toJson() => _$ProductToJson(this);
}
